/* ====== CAPITOLO 1 · LE BASI ======
   Nove interventi veri, dalla prima lampada al quadro che salta.
   Lo standard degli esercizi (docs/STANDARD.md) dice come si scrivono. */
import type { Level } from "../../core/types";
import { DIFF, PROBES3, Q_STD } from "../quadri";

export const CAP1: Level[] = [
  /* ---------- 1 ---------- */
  {
    id: "i1", n: 1, cap: 1, part: "Le basi", type: "fili",
    title: "Il giro", short: "Ricollega una lampada da comodino",
    note: "Con la spina che si gira, fase e neutro possono scambiarsi: qui i morsetti 1 e 2 sono equivalenti.",
    client: { who: "Zia Carla", where: "camera da letto", msg: "La lampada del comodino non si accende più. Ho guardato: i fili si sono staccati dal portalampada. Me la sistemi tu?" },
    learn: ["Cos'è un circuito e perché deve essere chiuso", "Volt, ampere, ohm, watt, e come passare dai watt agli ampere", "I colori dei fili di casa"],
    cards: ["giro", "ohm", "colori"],
    requires: ["circuito", "corto", "colori"],
    safety: { type: "spina" },
    board: {
      h: 300,
      zones: [{ id: "banco", x: 12, y: 12, w: 336, h: 276, label: "sul banco" }],
      cables: [{ x: 22, y: 250, w: 82, h: 18, label: "dalla spina" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "LP", kind: "lampada", x: 130, y: 42, zone: "banco", tlabel: { L: "1", N: "2" }, look: "portalampada" },
        { id: "cM", kind: "capo", color: "marrone", sec: 0.75, x: 120, y: 212, fx: 104, fy: 255, zone: "banco" },
        { id: "cB", kind: "capo", color: "blu", sec: 0.75, x: 250, y: 212, fx: 104, fy: 263, zone: "banco" },
      ],
      fixed: [{ a: "S.L", b: "cM.x" }, { a: "S.N", b: "cB.x" }],
    },
    palette: null,
    goal: { type: "lamp", lamp: "LP", mode: "sempre" },
    check: [
      { t: "Si spella solo il rame che entra nel morsetto", ok: true, why: "Il rame deve stare tutto dentro il morsetto: fuori diventa una parte scoperta in tensione." },
      { t: "Si stringono le viti e si tirano i fili per prova", ok: true, why: "Un morsetto lento scalda, e a volte il filo si sfila da solo." },
      { t: "Marrone e blu si possono unire attorcigliandoli, prima dei morsetti", ok: false, why: "Marrone e blu uniti insieme sono un cortocircuito: ogni filo va da solo nel suo morsetto." },
    ],
    hints: ["Ogni filo del cavo va a un morsetto diverso del portalampada.", "Marrone su un morsetto, blu sull'altro: così il giro passa dentro la lampadina."],
    solution: [["cM.x", "LP.L"], ["cB.x", "LP.N"]],
    mistakes: [{ name: "stesso morsetto", w: [["cM.x", "LP.L"], ["cB.x", "LP.L"]], expect: "corto" }],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Un bollitore da 2300 W: quanta corrente tira?", o: ["1 A", "10 A", "230 A"], ok: 1, why: "I = P ÷ V = 2300 ÷ 230 = 10 A." },
      { q: "Apri il giro in un punto qualsiasi. Cosa succede?", o: ["La corrente si ferma solo dopo il punto aperto", "La corrente si ferma in tutto il giro", "La corrente continua, più debole"], ok: 1, why: "La corrente scorre solo in un giro chiuso: aperto in un punto, si ferma ovunque. L'interruttore lavora così." },
      { q: "Il filo giallo-verde è…", o: ["La terra, e solo quella", "Il neutro negli impianti vecchi", "Una fase di riserva"], ok: 0, why: "Il giallo-verde si usa solo per la terra. Sempre." },
    ],
  },
  /* ---------- 2 ---------- */
  {
    id: "i2", n: 2, cap: 1, part: "Le basi", type: "fili",
    title: "La presa annerita", short: "Cambia una presa bruciacchiata in cucina",
    client: { who: "Sig.ra Ferri", where: "cucina", msg: "La presa vicino al bollitore è diventata nera e ogni tanto sento puzza di bruciato. Si può cambiare?" },
    learn: ["Perché un morsetto lento brucia una presa", "A cosa serve la terra", "La procedura prima di toccare: prova il tester, stacca, segnala, misura"],
    cards: ["joule", "terra", "presa", "procedura"],
    requires: ["terra", "procedura", "LN-morsetti", "rame-annerito"],
    safety: { type: "quadro", breakers: Q_STD, feed: "cucina", probes: PROBES3, where: "sui fili della presa" },
    board: {
      h: 340,
      zones: [{ id: "muro", x: 16, y: 14, w: 328, h: 300, label: "scatola 503 · cucina" }],
      cables: [{ x: 140, y: 284, w: 80, h: 18, label: "Cucina C16" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "PR", kind: "presa", x: 130, y: 46, zone: "muro" },
        { id: "cM", kind: "capo", color: "marrone", sec: 2.5, x: 100, y: 214, fx: 164, fy: 284, zone: "muro" },
        { id: "cG", kind: "capo", color: "gv", sec: 2.5, x: 180, y: 226, fx: 180, fy: 284, zone: "muro" },
        { id: "cB", kind: "capo", color: "blu", sec: 2.5, x: 260, y: 214, fx: 196, fy: 284, zone: "muro" },
      ],
      fixed: [{ a: "S.L", b: "cM.x" }, { a: "S.N", b: "cB.x" }, { a: "S.PE", b: "cG.x" }],
    },
    palette: null,
    goal: { type: "prese", prese: ["PR"] },
    check: [
      { t: "Il rame annerito si taglia e si spella di nuovo", ok: true, why: "Il rame ossidato e bruciato fa contatto male: scalderebbe di nuovo anche nella presa nuova." },
      { t: "Si stringono i morsetti e si tirano i fili per prova", ok: true, why: "È la causa del guasto: un morsetto lento scalda." },
      { t: "Se la presa è nuova, il rame scuro può restare", ok: false, why: "Il rame annerito ha più resistenza: il punto caldo si ripresenta nella presa nuova." },
    ],
    hints: ["Il giallo-verde va al morsetto della terra (⏚), quello centrale.", "Marrone e blu vanno ai due morsetti laterali: per la spina italiana il verso non conta."],
    solution: [["cM.x", "PR.A"], ["cB.x", "PR.B"], ["cG.x", "PR.PE"]],
    mistakes: [
      { name: "senza terra", w: [["cM.x", "PR.A"], ["cB.x", "PR.B"]], expect: "nonregola" },
      { name: "terra su un laterale", w: [["cM.x", "PR.A"], ["cG.x", "PR.B"], ["cB.x", "PR.PE"]], expect: "diff" },
      { name: "fase sulla terra", w: [["cG.x", "PR.A"], ["cM.x", "PR.PE"], ["cB.x", "PR.B"]], expect: "spento" },
      { name: "invertiti, va bene", w: [["cM.x", "PR.B"], ["cB.x", "PR.A"], ["cG.x", "PR.PE"]], expect: "ok" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Perché un morsetto lento fa scaldare la presa?", o: ["Fa passare più corrente", "Aggiunge resistenza, e il calore è R × I²", "Fa salire la tensione"], ok: 1, why: "La corrente è la stessa, ma nel punto di contatto c'è più resistenza: lì si concentra il calore." },
      { q: "Hai staccato al quadro, ma il tester segna 230 V tra fase e neutro. Cosa fai?", o: ["Lavoro con i guanti", "Il tester sarà rotto: lavoro lo stesso", "Ho staccato la linea sbagliata: torno al quadro"], ok: 2, why: "Il tester che segna tensione ha sempre ragione finché non provi il contrario. Torni al quadro, stacchi, rimisuri." },
      { q: "Nella presa bipasso il giallo-verde va…", o: ["Al morsetto della terra, quello del foro centrale", "A uno dei due morsetti laterali", "Si lascia libero se la presa è di plastica"], ok: 0, why: "La terra della presa serve all'apparecchio che ci attacchi, non alla presa: va sempre collegata." },
    ],
  },
  /* ---------- 3 ---------- */
  {
    id: "i3", n: 3, cap: 1, part: "Le basi", type: "fili",
    title: "Il lampadario", short: "Monta un lampadario di metallo al soffitto",
    note: "L'interruttore a muro è già collegato alla linea Luci C10: il suo ritorno sale nel tubo fino al soffitto.",
    client: { who: "Davide", where: "soggiorno", msg: "Ho preso un lampadario di metallo. Al soffitto adesso c'è solo una lampadina appesa ai fili. Me lo montate?" },
    learn: ["Tensione alternata: 230 V e 50 Hz", "Ritorno, fase diretta, neutro e terra al soffitto", "Perché l'interruttore a muro non basta", "Il morsetto a leva, e cosa fare di un filo che non serve"],
    cards: ["alternata", "ritorno", "classe", "muro", "morsetto"],
    requires: ["ritorno", "fase-diretta", "classe1", "muro", "morsetto-leva", "filo-non-usato"],
    safety: {
      type: "quadro", breakers: Q_STD, feed: "luci", wall: true, where: "sui fili al soffitto",
      probes: [
        { label: "Marrone – Blu", a: "L", b: "N" },
        { label: "Nero – Blu", a: "R", b: "N" },
        { label: "Marrone – Giallo-verde", a: "L", b: "PE" },
        { label: "Nero – Giallo-verde", a: "R", b: "PE" },
        { label: "Blu – Giallo-verde", a: "N", b: "PE" },
      ],
    },
    board: {
      h: 380,
      zones: [{ id: "soff", x: 132, y: 14, w: 212, h: 352, label: "soffitto" }, { id: "par", x: 12, y: 196, w: 112, h: 150, label: "parete" }],
      cables: [{ x: 138, y: 40, w: 112, h: 16, label: "dall'interruttore", from: "WS" }, { x: 256, y: 40, w: 84, h: 16, label: "Luci C10" }],
      tubes: [{ d: "M100,224 V64 Q100,48 116,48 H142", color: "nero", label: "ritorno", lx: 106, ly: 140, links: "WS" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "cN", kind: "capo", color: "nero", sec: 1.5, x: 194, y: 104, fx: 190, fy: 56, zone: "soff" },
        { id: "cM", kind: "capo", color: "marrone", sec: 1.5, x: 262, y: 104, fx: 266, fy: 56, zone: "soff" },
        { id: "cB", kind: "capo", color: "blu", sec: 1.5, x: 298, y: 110, fx: 292, fy: 56, zone: "soff" },
        { id: "cG", kind: "capo", color: "gv", sec: 1.5, x: 330, y: 104, fx: 318, fy: 56, zone: "soff" },
        { id: "W", kind: "morsetto", slots: 2, x: 262, y: 150, zone: "soff" },
        { id: "LP", kind: "lampada", classe1: true, look: "lampadario", top: true, x: 168, y: 228, zone: "soff" },
        { id: "WS", kind: "interruttore", x: 22, y: 224, zone: "par", locked: true, lockedMsg: "L'interruttore a muro è già collegato: prende la fase dalla linea Luci C10, e il suo ritorno sale nel tubo fino al soffitto. È il filo nero." },
      ],
      fixed: [
        { a: "S.L", b: "cM.x" }, { a: "S.L", b: "WS.1" }, { a: "WS.2", b: "cN.x" },
        { a: "S.N", b: "cB.x" }, { a: "S.PE", b: "cG.x" },
      ],
    },
    palette: null,
    goal: { type: "lamp", lamp: "LP", mode: "segue", sw: "WS" },
    check: [
      { t: "Il peso del lampadario va sul gancio al soffitto, non sui fili", ok: true, why: "I morsetti non sono fatti per reggere peso: il filo si sfila o si rompe dentro la guaina." },
      { t: "Il filo che non serve si chiude da solo in un morsetto", ok: true, why: "Un filo con il rame libero in una scatola è un contatto in attesa." },
      { t: "Per lavorare basta spegnere dall'interruttore a muro", ok: false, why: "Al soffitto restano le fasi dirette, e chiunque può riaccendere. Si stacca al quadro." },
    ],
    hints: ["Il nero è il ritorno che arriva dall'interruttore: va al morsetto L del lampadario. Blu al morsetto N, giallo-verde alla terra.", "Il marrone è una fase diretta: alla lampada non serve, ma non si lascia libero. Chiudilo da solo nel morsetto a leva."],
    solution: [["cN.x", "LP.L"], ["cB.x", "LP.N"], ["cG.x", "LP.PE"], ["cM.x", "W.s1"]],
    mistakes: [
      { name: "fase diretta alla lampada", w: [["cM.x", "LP.L"], ["cB.x", "LP.N"], ["cG.x", "LP.PE"], ["cN.x", "W.s1"]], expect: "sbagliato" },
      { name: "marrone libero", w: [["cN.x", "LP.L"], ["cB.x", "LP.N"], ["cG.x", "LP.PE"]], expect: "nonregola" },
      { name: "senza terra", w: [["cN.x", "LP.L"], ["cB.x", "LP.N"], ["cM.x", "W.s1"]], expect: "nonregola" },
      { name: "marrone e giallo-verde nello stesso morsetto", w: [["cN.x", "LP.L"], ["cB.x", "LP.N"], ["cM.x", "W.s1"], ["cG.x", "W.s2"]], expect: "diff" },
      { name: "marrone e nero insieme su L", w: [["cN.x", "LP.L"], ["cM.x", "LP.L"], ["cB.x", "LP.N"], ["cG.x", "LP.PE"]], expect: "sbagliato" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Hai spento la luce dall'interruttore a muro. Puoi lavorare al soffitto?", o: ["Sì, se la lampadina è spenta", "No: stacco al quadro, segnalo e misuro", "Sì, se l'interruttore è sulla fase"], ok: 1, why: "Al soffitto possono esserci fasi dirette, e qualcuno può riaccendere mentre lavori." },
      { q: "Il ritorno è…", o: ["Il filo che dall'interruttore porta la fase alla lampada", "Il neutro che torna verso il quadro", "Il filo di terra della lampada"], ok: 0, why: "A luce spenta il ritorno è a 0 V, a luce accesa porta la fase." },
      { q: "230 V è il valore efficace. Il picco della tensione è circa…", o: ["230 V", "325 V", "400 V"], ok: 1, why: "230 × √2 ≈ 325 V. I 400 V sono la tensione tra due fasi, negli impianti trifase." },
    ],
  },
  /* ---------- 4 ---------- */
  {
    id: "i4", n: 4, cap: 1, part: "Nuovi punti", type: "fili",
    title: "Il ripostiglio", short: "Un punto luce nuovo, con l'interruttore",
    note: "Nella scatola arriva la linea luci, lasciata pronta per questo punto. Il ritorno può andare dritto dall'interruttore alla plafoniera, oppure passare da un morsetto nella scatola.",
    client: { who: "Sig. Galli", where: "ripostiglio", msg: "Nel ripostiglio non c'è luce, entro col telefono in mano. Mi mettete una plafoniera e un interruttore vicino alla porta?" },
    learn: ["Perché l'interruttore va sulla fase", "Giunzioni in scatola, con i morsetti", "Che sezione usare per le luci"],
    cards: ["sullafase", "scatola", "sezione"],
    requires: ["interruttore-fase", "interruttore-simmetrico", "giunzioni", "sezione", "sezione-terra"],
    safety: { type: "quadro", breakers: Q_STD, feed: "luci", probes: PROBES3, where: "nella scatola di derivazione" },
    board: {
      h: 410,
      zones: [
        { id: "box", x: 16, y: 14, w: 206, h: 200, label: "scatola di derivazione" },
        { id: "porta", x: 232, y: 14, w: 116, h: 150, label: "alla porta" },
        { id: "soff", x: 60, y: 236, w: 240, h: 160, label: "soffitto" },
      ],
      cables: [{ x: 26, y: 38, w: 92, h: 16, label: "Luci C10" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "cM", kind: "capo", color: "marrone", sec: 1.5, x: 44, y: 96, fx: 52, fy: 54, zone: "box" },
        { id: "cB", kind: "capo", color: "blu", sec: 1.5, x: 104, y: 96, fx: 72, fy: 54, zone: "box" },
        { id: "cG", kind: "capo", color: "gv", sec: 1.5, x: 164, y: 96, fx: 92, fy: 54, zone: "box" },
        { id: "W1", kind: "morsetto", slots: 2, x: 28, y: 124, zone: "box" },
        { id: "W2", kind: "morsetto", slots: 2, x: 118, y: 124, zone: "box" },
        { id: "W3", kind: "morsetto", slots: 2, x: 28, y: 168, zone: "box" },
        { id: "W4", kind: "morsetto", slots: 2, x: 118, y: 168, zone: "box" },
        { id: "I", kind: "interruttore", x: 244, y: 50, zone: "porta" },
        { id: "LP", kind: "lampada", classe1: true, look: "plafoniera", top: true, x: 130, y: 272, zone: "soff" },
      ],
      fixed: [{ a: "S.L", b: "cM.x" }, { a: "S.N", b: "cB.x" }, { a: "S.PE", b: "cG.x" }],
    },
    palette: { sections: true, defSec: 1.5 },
    minSec: 1.5,
    goal: { type: "lamp", lamp: "LP", mode: "segue", sw: "I" },
    check: [
      { t: "Le giunzioni stanno nella scatola, nei morsetti", ok: true, why: "È l'unico posto dove si possono controllare e rifare." },
      { t: "La scatola resta ispezionabile, con il suo coperchio", ok: true, why: "Una scatola murata o coperta dalle piastrelle non si può più aprire." },
      { t: "Per fare prima si può giuntare nel tubo, con il nastro", ok: false, why: "Una giunzione nel tubo non si vede e non si raggiunge: quando scalda o si allenta, nessuno lo sa." },
    ],
    hints: ["Fase: dal morsetto della scatola a un morsetto dell'interruttore. Dall'altro morsetto parte il ritorno verso la L della plafoniera.", "Neutro e terra vanno dalla scatola alla plafoniera, ciascuno con il suo morsetto e il suo colore."],
    solution: [
      ["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"],
      ["W1.s2", "I.1", "marrone", 1.5], ["I.2", "LP.L", "nero", 1.5], ["W2.s2", "LP.N", "blu", 1.5], ["W3.s2", "LP.PE", "gv", 1.5],
    ],
    alternatives: [
      { name: "ritorno che passa dalla scatola", w: [["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"], ["W1.s2", "I.1", "marrone", 1.5], ["I.2", "W4.s1", "nero", 1.5], ["W4.s2", "LP.L", "nero", 1.5], ["W2.s2", "LP.N", "blu", 1.5], ["W3.s2", "LP.PE", "gv", 1.5]] },
    ],
    mistakes: [
      { name: "interruttore sul neutro", w: [["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"], ["W1.s2", "LP.L", "marrone", 1.5], ["W2.s2", "I.1", "blu", 1.5], ["I.2", "LP.N", "blu", 1.5], ["W3.s2", "LP.PE", "gv", 1.5]], expect: "nonregola" },
      { name: "ritorno blu", w: [["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"], ["W1.s2", "I.1", "marrone", 1.5], ["I.2", "LP.L", "blu", 1.5], ["W2.s2", "LP.N", "blu", 1.5], ["W3.s2", "LP.PE", "gv", 1.5]], expect: "nonregola" },
      { name: "corto all'interruttore", w: [["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"], ["W1.s2", "I.1", "marrone", 1.5], ["I.2", "W2.s2", "nero", 1.5]], expect: "corto" },
      { name: "neutro dimenticato", w: [["cM.x", "W1.s1"], ["cB.x", "W2.s1"], ["cG.x", "W3.s1"], ["W1.s2", "I.1", "marrone", 1.5], ["I.2", "LP.L", "nero", 1.5], ["W3.s2", "LP.PE", "gv", 1.5]], expect: "spento" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Se l'interruttore interrompe il neutro invece della fase…", o: ["La luce non si accende", "Salta il differenziale", "La luce funziona, ma a luce spenta la lampada resta in tensione"], ok: 2, why: "Funziona, ed è proprio per questo che è pericoloso: nessuno se ne accorge finché qualcuno non cambia la lampadina." },
      { q: "Dove si giuntano i fili?", o: ["In una scatola, con i morsetti", "Nel tubo, con il nastro isolante", "Dove capita, basta isolare bene"], ok: 0, why: "Le giunzioni devono restare ispezionabili." },
      { q: "La linea luci con magnetotermico da 10 A si fa di solito con…", o: ["0,75 mm²", "1,5 mm²", "6 mm²"], ok: 1, why: "1,5 mm² per le luci, 2,5 mm² per le prese." },
    ],
  },
  /* ---------- 5 ---------- */
  {
    id: "i5", n: 5, cap: 1, part: "Nuovi punti", type: "fili",
    title: "La presa per la TV", short: "Deriva una presa nuova, in canalina",
    note: "I morsetti della presa esistente accettano un secondo filo: da lì riparti verso la presa nuova. Canalina e scatola da esterno della presa nuova sono già montate.",
    trap: "etichette",
    client: { who: "Marta", where: "soggiorno", msg: "Mi serve una presa dietro la TV, a tre metri da quella che c'è già. Il muro non lo voglio rompere." },
    learn: ["Prese in parallelo e correnti che si sommano", "Il magnetotermico protegge il cavo: la sezione giusta", "Canalina: larghezza e altezza", "Perché le scritte del quadro possono mentire"],
    cards: ["parallelo", "protegge", "canalina", "etichette"],
    requires: ["morsetti-due-fili", "sezione-linea", "sezione-terra", "canalina", "etichette", "giunzioni"],
    safety: {
      type: "quadro", feed: "pcam", probes: PROBES3, where: "sulla presa esistente",
      breakers: [
        { id: "gen", label: "Generale", w: 1.6, kind: "gen" },
        DIFF,
        { id: "luci", label: "Luci", sub: "C10" },
        { id: "psog", label: "Prese soggiorno", sub: "C16" },
        { id: "pcam", label: "Prese camere", sub: "C16" },
        { id: "cucina", label: "Cucina", sub: "C16" },
      ],
    },
    shop: {
      q: "Canalina 30×10 bianca lungo il battiscopa, tre metri: due pezzi di canale da 2 m, un angolo interno, un angolo esterno, e alla fine il canale entra nella scatola da esterno dietro la TV (scatola e frutto li hai già nel furgone). Cosa prendi dallo scaffale, oltre al canale?",
      opts: [
        { t: "Angolo interno 30×10 bianco", ok: true, why: "Stessa larghezza, stessa altezza: si aggancia." },
        { t: "Angolo interno 30×20 bianco", ok: false, why: "La larghezza è giusta ma l'altezza no: il coperchio non si aggancia." },
        { t: "Angolo esterno 30×10 bianco", ok: true, why: "Giusto." },
        { t: "Angolo esterno 40×17 bianco", ok: false, why: "Misura diversa: non si aggancia al 30×10." },
        { t: "Giunto 30×10 bianco", ok: true, why: "Unisce i due pezzi di canale." },
      ],
    },
    board: {
      h: 360,
      zones: [{ id: "A", x: 16, y: 14, w: 158, h: 236, label: "presa esistente" }, { id: "B", x: 186, y: 14, w: 158, h: 236, label: "presa nuova" }],
      cables: [{ x: 50, y: 214, w: 90, h: 16, label: "Prese C16" }],
      canalina: { x: 40, y: 296, w: 280, label: "canalina 30×10 lungo il battiscopa" },
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "PA", kind: "presa", x: 45, y: 48, zone: "A" },
        { id: "PB", kind: "presa", x: 215, y: 48, zone: "B" },
      ],
      fixed: [
        { a: "S.L", b: "PA.A", vis: true, color: "marrone", sec: 2.5, from: { x: 70, y: 214 } },
        { a: "S.PE", b: "PA.PE", vis: true, color: "gv", sec: 2.5, from: { x: 95, y: 214 } },
        { a: "S.N", b: "PA.B", vis: true, color: "blu", sec: 2.5, from: { x: 120, y: 214 } },
      ],
    },
    palette: { sections: true, defSec: 1.5 },
    minSec: 2.5,
    goal: { type: "prese", prese: ["PA", "PB"] },
    check: [
      { t: "Il coperchio della canalina si chiude da solo, senza schiacciare i fili", ok: true, why: "Un filo schiacciato dal coperchio si rovina nel tempo." },
      { t: "Angoli e giunto devono essere 30×10, come il canale", ok: true, why: "Larghezza e altezza devono coincidere." },
      { t: "Se l'angolo non si aggancia, si fissa con il nastro", ok: false, why: "Era la misura sbagliata. Si torna al negozio, non si ripiega sul nastro." },
    ],
    hints: ["Ogni morsetto della presa esistente accetta un secondo filo: da lì riparti verso la presa nuova, morsetto per morsetto.", "La linea è da 16 A: i fili nuovi, terra compresa, devono essere da 2,5 mm². Scegli la sezione prima di tirarli, oppure tocca un filo e cambiala."],
    solution: [["PA.A", "PB.A", "marrone", 2.5], ["PA.B", "PB.B", "blu", 2.5], ["PA.PE", "PB.PE", "gv", 2.5]],
    mistakes: [
      { name: "sezione 1,5", w: [["PA.A", "PB.A", "marrone", 1.5], ["PA.B", "PB.B", "blu", 1.5], ["PA.PE", "PB.PE", "gv", 1.5]], expect: "nonregola" },
      { name: "incrociati, va bene", w: [["PA.A", "PB.B", "marrone", 2.5], ["PA.B", "PB.A", "blu", 2.5], ["PA.PE", "PB.PE", "gv", 2.5]], expect: "ok" },
      { name: "senza terra", w: [["PA.A", "PB.A", "marrone", 2.5], ["PA.B", "PB.B", "blu", 2.5]], expect: "nonregola" },
      { name: "fase e neutro sulla stessa presa", w: [["PA.A", "PB.A", "marrone", 2.5], ["PA.B", "PB.A", "blu", 2.5]], expect: "corto" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Due prese in parallelo sulla stessa linea. Ognuna riceve…", o: ["115 V, la metà", "230 V", "460 V, il doppio"], ok: 1, why: "In parallelo la tensione è la stessa per tutte. Sono le correnti a sommarsi." },
      { q: "Linea prese protetta da 16 A: con che sezione fai la derivazione?", o: ["1,5 mm², la TV consuma poco", "2,5 mm²", "Quella che avanza nel furgone"], ok: 1, why: "La sezione segue il magnetotermico, non l'apparecchio: domani su quella presa ci sarà una stufetta." },
      { q: "Il canale è 30×10. Quale angolo prendi?", o: ["30×20: la larghezza è uguale", "Uno qualsiasi, si adatta", "30×10, della stessa serie"], ok: 2, why: "Larghezza e altezza, e possibilmente la stessa serie." },
    ],
  },
  /* ---------- 6 ---------- */
  {
    id: "i6", n: 6, cap: 1, part: "I comandi", type: "fili",
    title: "Il corridoio", short: "Luce da due punti: la deviata",
    note: "Il vecchio interruttore all'inizio del corridoio è già stato tolto: al suo posto va il primo deviatore. Neutro e terra vanno già dalla scatola alla plafoniera, li ha collegati il collega: tu pensi alla fase e ai due deviatori.",
    client: { who: "Famiglia Conti", where: "corridoio", msg: "Il corridoio è lungo e l'interruttore è solo da una parte. La sera arriviamo in fondo al buio. Si può accendere da tutte e due le parti?" },
    learn: ["Come funziona un deviatore", "Lo schema della deviata", "Collaudare tutte le combinazioni"],
    cards: ["deviatore", "verita"],
    requires: ["deviatore", "scambi-colore", "verita"],
    safety: { type: "quadro", breakers: Q_STD, feed: "luci", probes: PROBES3, where: "nella scatola" },
    board: {
      h: 452,
      zones: [
        { id: "box", x: 108, y: 14, w: 144, h: 112, label: "scatola" },
        { id: "z1", x: 16, y: 146, w: 152, h: 136, label: "inizio corridoio" },
        { id: "z2", x: 192, y: 146, w: 152, h: 136, label: "fine corridoio" },
        { id: "soff", x: 90, y: 300, w: 180, h: 140, label: "soffitto" },
      ],
      cables: [{ x: 120, y: 34, w: 64, h: 14, label: "Luci C10" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "cM", kind: "capo", color: "marrone", sec: 1.5, x: 134, y: 92, fx: 140, fy: 48, zone: "box" },
        { id: "W1", kind: "morsetto", slots: 2, x: 180, y: 70, zone: "box" },
        { id: "D1", kind: "deviatore", x: 36, y: 172, zone: "z1" },
        { id: "D2", kind: "deviatore", x: 214, y: 172, zone: "z2" },
        { id: "LP", kind: "lampada", classe1: true, look: "plafoniera", top: true, x: 130, y: 340, zone: "soff" },
      ],
      fixed: [
        { a: "S.L", b: "cM.x" },
        { a: "S.N", b: "LP.N", vis: true, color: "blu", sec: 1.5, d: "M152,48 C152,112 176,104 176,150 V300 C176,326 180,326 180,352" },
        { a: "S.PE", b: "LP.PE", vis: true, color: "gv", sec: 1.5, d: "M164,48 C164,104 186,98 186,146 V296 C186,322 214,318 214,352" },
      ],
    },
    palette: { sections: true, defSec: 1.5 },
    minSec: 1.5,
    goal: { type: "lamp", lamp: "LP", mode: "commuta" },
    check: [
      { t: "I due fili di scambio corrono nello stesso tubo, uno accanto all'altro", ok: true, why: "I conduttori dello stesso circuito viaggiano insieme: è più ordinato e si riconoscono." },
      { t: "Nelle scatole si lascia un po' di filo in più, per lavorarci in futuro", ok: true, why: "Senza scorta, la prossima giunzione diventa un problema." },
      { t: "Al comune del secondo deviatore va il neutro", ok: false, why: "Il neutro va alla lampada. Dal comune del secondo deviatore parte il ritorno." },
    ],
    hints: ["La fase entra nel comune (C) del primo deviatore: dal morsetto della scatola tira un filo marrone fino a C.", "Le uscite 1 e 2 del primo vanno alle uscite 1 e 2 del secondo. Dal comune del secondo parte il ritorno verso la L della lampada."],
    solution: [["cM.x", "W1.s1"], ["W1.s2", "D1.C", "marrone", 1.5], ["D1.1", "D2.1", "nero", 1.5], ["D1.2", "D2.2", "grigio", 1.5], ["D2.C", "LP.L", "nero", 1.5]],
    mistakes: [
      { name: "fase su un'uscita", w: [["cM.x", "W1.s1"], ["W1.s2", "D1.1", "marrone", 1.5], ["D1.C", "D2.1", "nero", 1.5], ["D1.2", "D2.2", "grigio", 1.5], ["D2.C", "LP.L", "nero", 1.5]], expect: "sbagliato" },
      { name: "scambi incrociati, va bene", w: [["cM.x", "W1.s1"], ["W1.s2", "D1.C", "marrone", 1.5], ["D1.1", "D2.2", "nero", 1.5], ["D1.2", "D2.1", "grigio", 1.5], ["D2.C", "LP.L", "nero", 1.5]], expect: "ok" },
      { name: "uno scambio solo", w: [["cM.x", "W1.s1"], ["W1.s2", "D1.C", "marrone", 1.5], ["D1.1", "D2.1", "nero", 1.5], ["D2.C", "LP.L", "nero", 1.5]], expect: "sbagliato" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Quanti fili collegano tra loro i due deviatori?", o: ["Uno", "Due, i fili di scambio", "Tre"], ok: 1, why: "Le due uscite del primo vanno alle due uscite del secondo." },
      { q: "Dove arriva la fase in una deviata?", o: ["Al comune del primo deviatore", "A un'uscita del primo deviatore", "Direttamente alla lampada"], ok: 0, why: "Fase al comune del primo, ritorno dal comune del secondo." },
      { q: "Con due deviatori, quante combinazioni deve provare il collaudo?", o: ["2", "4", "8"], ok: 1, why: "2 posizioni × 2 posizioni = 4." },
    ],
  },
  /* ---------- 7 ---------- */
  {
    id: "i7", n: 7, cap: 1, part: "I comandi", type: "fili",
    title: "La camera", short: "Luce da tre punti: l'invertitore",
    note: "Neutro e terra vanno già dalla scatola alla plafoniera: li ha collegati il collega. Tu pensi alla fase, ai deviatori e all'invertitore.",
    client: { who: "Luca e Sara", where: "camera da letto", msg: "In camera vorremmo accendere la luce dalla porta e da tutti e due i comodini. Si può?" },
    learn: ["L'invertitore e la luce da tre punti", "Quando conviene il relè passo-passo"],
    cards: ["invertitore", "rele"],
    requires: ["invertitore-coppie", "deviatore", "scambi-colore", "verita"],
    safety: { type: "quadro", breakers: Q_STD, feed: "luci", probes: PROBES3, where: "nella scatola" },
    board: {
      h: 452,
      zones: [
        { id: "box", x: 108, y: 14, w: 144, h: 106, label: "scatola" },
        { id: "z1", x: 16, y: 138, w: 152, h: 134, label: "porta" },
        { id: "zi", x: 180, y: 138, w: 164, h: 134, label: "primo comodino" },
        { id: "z2", x: 16, y: 290, w: 152, h: 152, label: "secondo comodino" },
        { id: "soff", x: 180, y: 290, w: 164, h: 152, label: "soffitto" },
      ],
      cables: [{ x: 120, y: 34, w: 64, h: 14, label: "Luci C10" }],
      comps: [
        { id: "S", kind: "sorgente" },
        { id: "cM", kind: "capo", color: "marrone", sec: 1.5, x: 134, y: 90, fx: 140, fy: 48, zone: "box" },
        { id: "W1", kind: "morsetto", slots: 2, x: 180, y: 64, zone: "box" },
        { id: "D1", kind: "deviatore", x: 36, y: 162, zone: "z1" },
        { id: "INV", kind: "invertitore", x: 197, y: 162, zone: "zi" },
        { id: "D2", kind: "deviatore", x: 36, y: 316, zone: "z2" },
        { id: "LP", kind: "lampada", classe1: true, look: "plafoniera", top: true, x: 212, y: 330, zone: "soff" },
      ],
      fixed: [
        { a: "S.L", b: "cM.x" },
        { a: "S.N", b: "LP.N", vis: true, color: "blu", sec: 1.5, d: "M152,48 C152,104 172,96 172,146 V272 C172,282 182,286 196,286 H246 C258,286 262,302 262,342" },
        { a: "S.PE", b: "LP.PE", vis: true, color: "gv", sec: 1.5, d: "M164,48 C164,100 176,92 176,140 V266 C176,276 186,279 198,279 H280 C292,279 296,302 296,342" },
      ],
    },
    palette: { sections: true, defSec: 1.5 },
    minSec: 1.5,
    goal: { type: "lamp", lamp: "LP", mode: "commuta" },
    check: [
      { t: "L'invertitore sta in mezzo: riceve gli scambi del primo deviatore e li manda al secondo", ok: true, why: "È l'unico posto in cui può stare." },
      { t: "Al collaudo si provano tutte e 8 le combinazioni, non una sola", ok: true, why: "Con tre punti un errore può nascondersi in una sola combinazione su otto." },
      { t: "L'invertitore può stare al posto del primo deviatore: i morsetti sono simili", ok: false, why: "Il deviatore ha 3 morsetti e devia la fase; l'invertitore ne ha 4 e incrocia gli scambi. Non si scambiano." },
    ],
    hints: ["Fase al comune del primo deviatore. Le sue uscite 1 e 2 entrano nella coppia 1-2 dell'invertitore.", "Dalla coppia 3-4 dell'invertitore i fili vanno alle uscite del secondo deviatore, e dal suo comune parte il ritorno alla lampada."],
    solution: [["cM.x", "W1.s1"], ["W1.s2", "D1.C", "marrone", 1.5], ["D1.1", "INV.1", "nero", 1.5], ["D1.2", "INV.2", "grigio", 1.5], ["INV.3", "D2.1", "nero", 1.5], ["INV.4", "D2.2", "grigio", 1.5], ["D2.C", "LP.L", "nero", 1.5]],
    mistakes: [
      { name: "coppie sbagliate", w: [["cM.x", "W1.s1"], ["W1.s2", "D1.C", "marrone", 1.5], ["D1.1", "INV.1", "nero", 1.5], ["D1.2", "INV.3", "grigio", 1.5], ["INV.2", "D2.1", "nero", 1.5], ["INV.4", "D2.2", "grigio", 1.5], ["D2.C", "LP.L", "nero", 1.5]], expect: "sbagliato" },
    ],
    stars: ["Sicurezza", "Regola d'arte", "Al primo colpo"],
    quiz: [
      { q: "Per accendere una luce da tre punti servono…", o: ["3 deviatori", "2 deviatori e 1 invertitore", "3 interruttori"], ok: 1, why: "Deviatori agli estremi, invertitori in mezzo." },
      { q: "Cosa fa l'invertitore quando lo giri?", o: ["Interrompe la fase", "Incrocia i due fili di scambio", "Scambia fase e neutro"], ok: 1, why: "In una posizione li lascia dritti, nell'altra li incrocia." },
      { q: "Con tanti punti di comando, cosa conviene?", o: ["Pulsanti e relè passo-passo", "Un invertitore per punto, sempre", "Un interruttore per ogni lampadina"], ok: 0, why: "Con il relè ogni punto in più è solo un pulsante in parallelo." },
    ],
  },
  /* ---------- 8 ---------- */
  {
    id: "i8", n: 8, cap: 1, part: "Il quadro e i guasti", type: "indagine",
    title: "Salta tutto", short: "Trova la causa, con metodo",
    client: { who: "Sig. Russo", where: "tutta la casa", msg: "Da ieri, appena parte la lavatrice, salta tutto e resto al buio. Ho rialzato la levetta tre volte, ma ricapita." },
    learn: ["Come ragiona il differenziale", "Cosa fa la corrente al corpo", "Differenziale puro o magnetotermico, e i tipi AC, A, F, B", "Il metodo per trovare il guasto"],
    cards: ["leggi", "differenziale", "corpo", "tipi", "metodo"],
    requires: ["quadro-lettura", "differenziale", "metodo", "terra"],
    ind: {
      sintomo: "Appena parte la lavatrice, salta tutto e la casa resta al buio.",
      bet: { q: "Scommetti prima di guardare il quadro: cosa salta?", o: ["Il contatore: troppa potenza", "Un magnetotermico: un corto", "Il differenziale: una dispersione"], ok: 2 },
      soglia: 22,
      breakers: [
        { id: "gen", label: "Generale", w: 1.6, kind: "gen" },
        DIFF,
        { id: "luci", label: "Luci", sub: "C10" },
        { id: "prese", label: "Prese", sub: "C16" },
        { id: "lav", label: "Lavanderia", sub: "C16" },
      ],
      apps: [
        { id: "frigo", label: "Frigorifero", a: "il frigorifero", line: "prese", leak: 1.5 },
        { id: "tv", label: "TV", a: "la TV", line: "prese", leak: 0.5 },
        { id: "lamp", label: "Lampada da terra", a: "la lampada da terra", line: "prese", leak: 0.2 },
        { id: "lavat", label: "Lavatrice", a: "la lavatrice", line: "lav", leak: 42, colpa: true },
      ],
      chi: [
        { id: "frigo", t: "Il frigorifero", why: "Il frigorifero resta attaccato anche quando il differenziale regge: non è lui." },
        { id: "lavat", t: "La lavatrice", why: "Il differenziale regge finché la lavatrice è staccata, anche con la sua linea accesa, e scatta appena la riattacchi: il guasto è dentro la lavatrice." },
        { id: "linea", t: "I fili della linea lavanderia", why: "Con la lavatrice staccata e il magnetotermico della lavanderia su, il differenziale regge: i fili della linea sono a posto." },
        { id: "diff", t: "Il differenziale, che è difettoso", why: "Il differenziale fa il suo lavoro: regge finché la lavatrice è staccata, e stacca quando c'è la dispersione." },
      ],
      cosa: [
        { t: "Lascio la lavatrice staccata e la faccio controllare da un tecnico", ok: true, why: "Ha una dispersione verso terra: probabilmente la resistenza che scalda l'acqua. Finché non si ripara, resta staccata." },
        { t: "Faccio un ponticello sul differenziale, così la lavatrice va", ok: false, why: "Così togli la protezione a tutta la casa, e la carcassa della lavatrice resta con una dispersione: è esattamente il caso per cui esiste il differenziale." },
        { t: "Metto un differenziale meno sensibile, da 300 mA", ok: false, why: "300 mA non proteggono le persone. Il guasto resta, e smetti solo di vederlo." },
      ],
    },
    stars: ["Metodo", "Diagnosi", "Sicurezza"],
    quiz: [
      { q: "Il differenziale scatta quando…", o: ["La corrente supera i 16 A", "Sulla fase esce più corrente di quella che torna dal neutro", "La tensione supera i 230 V"], ok: 1, why: "Guarda la differenza: se manca qualcosa al ritorno, sta andando a terra." },
      { q: "Tocchi fase e neutro insieme, isolato da terra. Il differenziale…", o: ["Scatta subito", "Scatta dopo un secondo", "Non scatta: per lui sei un carico"], ok: 2, why: "La corrente esce dalla fase e torna tutta dal neutro, passando da te. Nessuna differenza da vedere." },
      { q: "La lavatrice fa scattare il differenziale. Cosa fai?", o: ["La lascio staccata e la faccio controllare", "Ponticello il differenziale", "Metto un differenziale da 300 mA"], ok: 0, why: "Il guasto è nell'apparecchio. La protezione non si tocca." },
    ],
  },
  /* ---------- 9 ---------- */
  {
    id: "i9", n: 9, cap: 1, part: "Il quadro e i guasti", type: "serata",
    title: "Salta il contatore", short: "Potenza, contratto, e la ciabatta che scalda",
    client: { who: "Elena", where: "tutta la casa", msg: "La sera, se accendo forno e lavatrice insieme, si spegne tutta la casa. Ma al quadro le levette sono tutte su!" },
    learn: ["Potenza, watt e ampere", "Il contatore e la potenza del contratto", "Termico e magnetico", "La ciabatta che il quadro non vede"],
    cards: ["potenza", "contatore", "mt", "ciabatta"],
    requires: ["potenza", "contatore", "ciabatta"],
    ser: {
      contratti: [3, 4.5, 6],
      tempi: { contatore: 4, ciabatta: 2, insieme: 3 },
      missioni: [{ cosa: "contatore" }, { cosa: "insieme", app: ["forno", "lavat"], azione: "contratto" }, { cosa: "ciabatta", app: ["phon", "stufa"] }],
      lines: [
        { id: "cucina", label: "Cucina", mt: 16, apps: [{ id: "frigo", label: "Frigorifero", w: 150, on: true }, { id: "forno", label: "Forno", w: 2000 }, { id: "boll", label: "Bollitore", w: 2000 }] },
        { id: "lav", label: "Lavanderia", mt: 16, apps: [{ id: "lavat", label: "Lavatrice", w: 2000 }] },
        { id: "camera", label: "Camera", mt: 16, ciabatta: 10, apps: [{ id: "phon", label: "Phon", w: 1800, ciab: true }, { id: "stufa", label: "Stufetta", w: 2000, ciab: true }, { id: "carica", label: "Caricatore", w: 20 }, { id: "tv", label: "TV", w: 100 }] },
        { id: "luci", label: "Luci", mt: 10, apps: [{ id: "luci", label: "Luci di casa", w: 150, on: true }] },
      ],
    },
    stars: ["Contatore capito", "Serata salvata", "Pericolo trovato"],
    quiz: [
      { q: "Contratto da 3 kW: fino a che potenza puoi stare senza limiti di tempo?", o: ["3 kW esatti", "3,3 kW", "4,5 kW"], ok: 1, why: "La potenza disponibile è quella del contratto più il 10%." },
      { q: "Una ciabatta da 10 A regge al massimo circa…", o: ["1000 W", "2300 W", "3500 W"], ok: 1, why: "10 A × 230 V = 2300 W." },
      { q: "Il magnetotermico da 16 A scatta all'istante con…", o: ["17 A", "20 A per un minuto", "Un cortocircuito, centinaia di ampere"], ok: 2, why: "Il magnetico di un C16 interviene tra 80 e 160 A. Sopra i 16 A, ma vicino, lavora il termico, che è lento." },
    ],
  },
];
